CREATE TABLE sources (
	id INTEGER UNSIGNED NOT NULL,
	type VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE articlefeatures (
	id INTEGER UNSIGNED NOT NULL,
	type VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	score DOUBLE NOT NULL,
	articleId INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE articles (
	id INTEGER UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	publishedAt VARCHAR(255) NOT NULL,
	discoveredAt VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	topicId INTEGER UNSIGNED,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE topics (
	id INTEGER UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE incomingarticles (
	id INTEGER UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	publishedAt DATETIME NOT NULL,
	discoveredAt DATETIME NOT NULL,
	sourceId INTEGER UNSIGNED,
	address VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE topicfeatures (
	id INTEGER UNSIGNED NOT NULL,
	type VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	score DOUBLE NOT NULL,
	topicId INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

