CREATE TABLE articles (
	id INTEGER UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	publishedAt VARCHAR(255) NOT NULL,
	discoveredAt VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	topicId INTEGER UNSIGNED,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE topics (
	id INTEGER UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE sources (
	id INTEGER UNSIGNED NOT NULL,
	type VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE incomingarticles (
	id INTEGER UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	publishedAt DATETIME NOT NULL,
	discoveredAt DATETIME NOT NULL,
	sourceId INTEGER UNSIGNED,
	address VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE INDEX topic ON articles (topicId ASC);

CREATE INDEX source ON incomingarticles (sourceId ASC);

